### ISSUE TITLE
Release Notes link broken

### ISSUE THREAD

**Issue by llaville** [DamienHarper/auditor-docs#9]
Hello Damien,

I just have a look on your online documentation available at https://damienharper.github.io/auditor-docs/docs/auditor/index.html, and realized that the `Release notes` link on Getting Started section is broken.

Gave a 404 error with : `https://damienharper.github.io/auditor-docshttps://github.com/DamienHarper/auditor/releases`

I don't know Couscous CMS, so I can't help you but source definition is at https://github.com/DamienHarper/auditor-docs/blob/master/couscous.yml#L38

**Comment by llaville** [comment]
Same issue with `auditor-bundle` docs and `Release notes` link defined at https://github.com/DamienHarper/auditor-docs/blob/master/couscous.yml#L67

**Comment by DamienHarper** [comment]
@llaville Thanks for the report, I already noticed it but hadn't time to fix it yet. It seems related to the way Couscous handles links (it might not support full absolute links :/ I need to investigate)

**Comment by llaville** [comment]
After having a look on your source code, I've noticed that menu is generated by twig macro https://github.com/DamienHarper/auditor-docs/blob/master/template/helper.twig#L12

You need to update it and check if protocol is set before to prepend baseUrl

**Comment by DamienHarper** [comment]
Good catch, thanks @llaville

**Comment by DamienHarper** [comment]
Fixed!
